version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - run:
          name: git clone
          command: git clone https://github.com/johnrigler/unspendable
      - run:
          name: ∆∆∆ 
          command: ./unspendable 
