version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - run:
          name: ∆∆∆ 
          command: python --version
     -  run:
         name: fsdfsdf
         command: ls

