version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    steps:
      - run:
          name: git clone
          commnd: git clone https://johnrigler/unspendable
      - run:
          name: ∆∆∆ 
          command: cd /; find . | grep unspendable 
